Title: Techihub
short_title: TH
Slogan: Technology for Everyone
baseurl: "/"
url: "https://techihub.github.io"
Author: Nadirsha Aliyar
Author_img: "/static/IMG/"
disqus_shortname: https-chipprogrammers-github-io-pimate
addthis_id: ra-5aa39bfee6d7726e
logo: "/static/IMG/chip.svg"
favicon: "/assets/img/chip.ico"

enableTags: true
tagarray: []

paginate: 4
paginate_path: "/blog/page:num/"
highlighter: rouge
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
